# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/superbderrick/DerrickFrameworkSpec.git'

target 'DerrickFrameworkSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DerrickFrameworkSample

  pod 'DerrickFramework','0.1.0'

end
